### ISSUE TITLE
I don't have permission to download the pre-training model, can you give me permission to download it?

### ISSUE THREAD

**Issue by SuperCarryFu** [LinQinLiang/SSAH-adversarial-attack#1]

**Comment by LinQinLiang** [comment]
It,s ok now.

**Comment by SuperCarryFu** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LinQinLiang/SSAH-adversarial-attack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月1日(星期五) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LinQinLiang/SSAH-adversarial-attack] I don't have permission to download the pre-training model, can you give me permission to download it? (Issue #1)





 
It,s ok now.

**Comment by LinQinLiang** [comment]
We have released the download link permission.
